name: manual / Release

on:
  workflow_dispatch:
    inputs:
      adjustment:
        description: 'Release increment type. Defaults to "minor", available values are "major", "minor" and "patch"'
        required: true
        default: 'minor'

permissions:
  contents: write

env:
  REVISIONS_RELEASE: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Validate adjustment
        run: |
          case "${{ github.event.inputs.adjustment }}" in
            major|minor|patch) ;;
            *) echo "Invalid adjustment"; exit 1 ;;
          esac

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup project
        uses: ./.github/actions/setup-clojure-project

      - name: Inject revision increment adjustment
        run: echo "REVISIONS_ADJUSTMENT=${{ github.event.inputs.adjustment }}" >> $GITHUB_ENV

      - name: Extract version
        id: version
        run: echo "version=$(lein pprint :version | tr -d '\"')" >> $GITHUB_OUTPUT

      - name: Create tag
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{steps.version.outputs.version}}",
              sha: context.sha
            })

      - name: Deploy to Clojars
        run: lein deploy clojars
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_TOKEN: ${{ secrets.CLOJARS_TOKEN }}
